name: Build iOS App
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Briefcase
        run: |
          python -m pip install --upgrade pip
          pip install briefcase

      - name: Create iOS App
        run: |
          briefcase create ios --no-input

      - name: Build iOS App
        run: |
          # Собираем проект, отключая проверку сертификатов на уровне системы
          briefcase build ios --no-input --device -- -codeSignIdentity="" -codeSignStyle=Manual CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO AD_HOC_CODE_SIGNING_ALLOWED=YES

      - name: Upload App Package
        uses: actions/upload-artifact@v4
        with:
          name: ios-app-bundle
          # Сохраняем все найденные .app папки
          path: build/**/*.app
          if-no-files-found: error
